# Generated by Django 4.1.5 on 2023-01-11 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='number',
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.CharField(default='just to fill', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
